# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('kraj_pochodzenia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('moc', models.IntegerField()),
                ('pojemnosc', models.IntegerField()),
                ('przebieg', models.IntegerField()),
                ('paliwo', models.CharField(max_length=20)),
                ('nadwozie', models.CharField(max_length=20)),
                ('kolor', models.CharField(max_length=20)),
                ('cena', models.IntegerField()),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Marka')),
            ],
        ),
        migrations.DeleteModel(
            name='Adres',
        ),
        migrations.DeleteModel(
            name='Osoba',
        ),
    ]
