# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170522_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('haslo', models.CharField(max_length=20)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=25)),
                ('telefon', models.IntegerField()),
            ],
        ),
    ]
