# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_samochod_uzytkownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marka',
            name='nazwa',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
