# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_samochod_uzytkownik'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='rok',
            field=models.IntegerField(default=1990),
            preserve_default=False,
        ),
    ]
