# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20170523_2201'),
        ('app1', '0006_auto_20170604_1239'),
    ]

    operations = [
    ]
