# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0007_merge_20170605_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='haslo',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='login',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marka',
            name='nazwa',
            field=models.CharField(max_length=30),
        ),
    ]
