# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20170611_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='Imie',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='Nazwisko',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
