# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20170611_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='Imie',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='Nazwisko',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
